apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counter-backend-hpa
  namespace: 254501-samready
  labels:
    app.kubernetes.io/part-of: counter-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-backend
  maxReplicas: 3
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
