apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-database-data
  namespace: 254501-samready
  labels:
    app.kubernetes.io/part-of: counter-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rbd-storagepool-cluster
  volumeMode: Filesystem