apiVersion: v1
kind: Service
metadata:
  name: counter-database
  labels:
    app: counter-database
    app.kubernetes.io/part-of: counter-app
  namespace: 254501-samready
spec:
  selector:
    app: counter-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
